# Javascript Node CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      # Node versions used
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing Packages
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Linter
          command: yarn lint

      - run:
          name: Running Tests with Coverage
          command: yarn test:coveralls

workflows:
  version: 2
  build-it:
    jobs:
      - build
